### PR TITLE
[TEST PR - NO MERGE] tweak CIs to test locking fix

### PR DESCRIPTION
**Pull request by msarahan**

### CODE REVIEW

**Comment by msarahan** [comment]
Looks fine, @jakirkham?  Shall I merge that conda-build PR?

**Comment by jakirkham** [comment]
Go for it.

The AppVeyor Python 3.4 64-bit failure is a bit weird though as I thought we had fixed that, but it is unrelated to this change.

**Comment by msarahan** [comment]
Yes, that is strange. It should be gone on master. I will look more
carefully at it.

**Comment by msarahan** [comment]
The issue appears to be that the wrong python (root python) is the one actually being used for installing.  As a result, the build prefix has no files in it.

https://ci.appveyor.com/project/conda-forge/apptools-feedstock/build/1.0.12/job/676y8margbnhvun4#L1189

I'll try to track this down soon.

**Comment by msarahan** [comment]
Very interesting data point here:
- root env 2.7: builds 2.7, 3.4, 3.5 OK.
- root env 3.5: builds 2.7, 3.5 OK.  Fails to import apptools.

Not sure yet where that points.  I have fixed part of the issue in https://github.com/conda/conda-build/pull/933, but this is not done.

**Comment by jakirkham** [comment]
Do you still need this testing PR, @msarahan, or is this now resolved?

**Comment by msarahan** [comment]
This one is fixed

**Pull request closed without merging**
